#
# This source file is part of the My Heart Counts iOS open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

version: 2
multi-ecosystem-groups:
  weekly-dependencies:
    schedule:
      interval: "weekly"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "weekly-dependencies"
  - package-ecosystem: "swift"
    directory: "/MyHeartCountsShared"
    patterns: ["*"]
    multi-ecosystem-group: "weekly-dependencies"
