#
# This source file is part of the My Heart Counts iOS application based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

codecov:
  branch: main
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,files,footer
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 90.0
  round: up
  status:
    patch:
      default:
        target: auto
        threshold: 5.0
    project:
      default:
        target: auto
        threshold: 5.0
ignore:
- ^MyHeartCountsUITests.*
- ^MyHeartCountsTests.*
- "MyHeartCounts/Utils/Debug Stuff/**"
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
