#
# This source file is part of the My Heart Counts iOS application based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

default_platform(:ios)

APP_CONFIG = {
  default_environment: "staging",
  default_app_identifier: "edu.stanford.MyHeartCounts",
  default_secondary_app_identifier: "edu.stanford.MyHeartCounts.watchkitapp",
  default_provisioningProfile: "My Heart Counts - Biodesign Digital Health",
  default_secondary_provisioningProfile: "My Heart Counts - Biodesign Digital Health - Watch",
  default_version_name: "4.0.0",
  default_release_notes: "Bug fixes and performance improvements.",
  scheme: "MyHeartCounts",
  plist_path: "MyHeartCounts/Supporting Files/Info.plist"
}.freeze

platform :ios do
  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "5"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6"
  end

  desc "Build and Test UI Tests"
  lane :uitest do
    run_tests(
      scheme: "MyHeartCounts",
      skip_build: true,
      testplan: "MyHeartCounts UI Tests",
      derived_data_path: ".derivedData",
      code_coverage: true,
      devices: ["iPhone 17 Pro Max (26.1)"],
      disable_slide_to_type: false,
      concurrent_workers: 1,
      max_concurrent_simulators: 1,
      result_bundle: true,
      result_bundle_path: "./MyHeartCounts-UITests.xcresult",
      output_directory: ".",
      xcargs: [
        "-skipPackagePluginValidation",
        "-skipMacroValidation"
      ]
    )
  end

  desc "Screenshots"
  lane :screenshots do
    run_tests(
      scheme: "MyHeartCounts",
      destination: "generic/platform=iOS Simulator",
      configuration: "Debug",
      derived_data_path: ".derivedData",
      xcargs: [
        "-skipPackagePluginValidation",
        "-skipMacroValidation"
      ],
      build_for_testing: true
    )

    snapshot(
      test_without_building: true,
      derived_data_path: ".derivedData",
      devices: [
        "iPhone 17 Pro Max",
        "iPad Pro 13-inch (M4)"
      ],
      languages: [
         "en-US",
      ],
      scheme: APP_CONFIG[:scheme],
      output_directory: "./fastlane/screenshots",
      clear_previous_screenshots: true,
      concurrent_simulators: false,
      stop_after_first_error: true,
      skip_open_summary: true
    )
    
    # Workaround for https://github.com/fastlane/fastlane/issues/21759 and 
    Dir.glob("./screenshots/**/iPhone 17 Pro Max-*.png").each do |file|
      sh("sips --resampleHeightWidth 2796 1290 '#{file}'")
    end
  end

  desc "CodeQL"
  lane :codeql do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "320" # CodeQL runs on GitHub CI. We need much higher timeout here.
    build_app(
      scheme: APP_CONFIG[:scheme],
      skip_archive: true,
      skip_codesigning: true,
      derived_data_path: ".derivedData",
      xcargs: [
        "-skipPackagePluginValidation",
        "-skipMacroValidation"
      ]
    )
  end

  desc "Build app"
  lane :build do
    build_app(
      scheme: APP_CONFIG[:scheme],
      skip_archive: true,
      skip_codesigning: true,
      derived_data_path: ".derivedData",
      xcargs: [
        "-skipPackagePluginValidation",
        "-skipMacroValidation"
      ]
    )
  end

  desc "Archive app"
  lane :archive do |options|
    appidentifier = options[:appidentifier].to_s.strip.empty? ? APP_CONFIG[:default_app_identifier] : options[:appidentifier]
    secondaryAppIdentifier = options[:secondaryAppidentifier].to_s.strip.empty? ? APP_CONFIG[:default_secondary_app_identifier] : options[:secondaryAppidentifier]
    provisioningProfile = options[:provisioningProfile].to_s.strip.empty? ? APP_CONFIG[:default_provisioningProfile] : options[:provisioningProfile]
    secondaryProvisioningProfile = options[:secondaryProvisioningProfile].to_s.strip.empty? ? APP_CONFIG[:default_secondary_provisioningProfile] : options[:secondaryProvisioningProfile]

    update_app_identifier(
      plist_path: APP_CONFIG[:plist_path],
      app_identifier: appidentifier
    )

    build_app(
      scheme: APP_CONFIG[:scheme],
      derived_data_path: ".derivedData",
      skip_profile_detection: true,
      xcargs: [
        "-skipPackagePluginValidation",
        "-skipMacroValidation"
      ],
      export_options: {
        provisioningProfiles: {
          appidentifier => provisioningProfile,
          secondaryAppIdentifier => secondaryProvisioningProfile
        }
      }
    )
  end

  desc "Sign in to the App Store Connect API"
  lane :signin do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_BASE64"],
      is_key_content_base64: true
    )
  end

  desc "Publish a release to TestFlight or the App Store depending on the environment"
  lane :deploy do |options|
    environment = options[:environment].to_s.strip.empty? ? APP_CONFIG[:default_environment] : options[:environment]
    appidentifier = options[:appidentifier].to_s.strip.empty? ? APP_CONFIG[:default_app_identifier] : options[:appidentifier]
    secondaryAppIdentifier = options[:secondaryAppidentifier].to_s.strip.empty? ? APP_CONFIG[:default_secondary_app_identifier] : options[:secondaryAppidentifier]
    provisioningProfile = options[:provisioningProfile].to_s.strip.empty? ? APP_CONFIG[:default_provisioningProfile] : options[:provisioningProfile]
    secondaryProvisioningProfile = options[:secondaryProvisioningProfile].to_s.strip.empty? ? APP_CONFIG[:default_secondary_provisioningProfile] : options[:secondaryProvisioningProfile]
    versionname = options[:versionname].to_s.strip.empty? ? APP_CONFIG[:default_version_name] : options[:versionname]
    releasenotes = options[:releasenotes].to_s.strip.empty? ? APP_CONFIG[:default_release_notes] : options[:releasenotes]
    strip_sensorkit_entitlement = options[:strip_sensorkit_entitlement].to_s == "true"

    UI.message("Using environment: #{environment}")
    UI.message("Using app identifier: #{appidentifier}")
    UI.message("Using secondary app identifier: #{secondaryAppIdentifier}")
    UI.message("Using provisioning profile: #{provisioningProfile}")
    UI.message("Using secondary provisioning profile: #{secondaryProvisioningProfile}")
    UI.message("Using version name: #{versionname}")
    UI.message("Using release notes: #{releasenotes}")

    releasenotes = releasenotes.gsub('\u2019', "'")

    if environment == "production"
      increment_version_number(
        version_number: versionname
      )
    end
    
    signin
    latest_build_number = latest_testflight_build_number(
      app_identifier: appidentifier
    )
    increment_build_number(
      build_number: latest_build_number + 1
    )

    if strip_sensorkit_entitlement
      puts 'Stripping SensorKit entitlement'
      sh('plutil', '-remove', 'com\.apple\.developer\.sensorkit\.reader\.allow', '../MyHeartCounts/Supporting Files/MyHeartCounts.entitlements')
    end

    archive(
      appidentifier: appidentifier,
      secondaryAppIdentifier: secondaryAppIdentifier,
      provisioningProfile: provisioningProfile,
      secondaryProvisioningProfile: secondaryProvisioningProfile,
    )
    commit = last_git_commit
    
    if environment == "production"
      # For our 4.0 beta releases, we currently only use TestFlight in a larger release group.
      # deliver(
      #   app_identifier: appidentifier,
      #   release_notes: {
      #     'en-US' => releasenotes
      #   },
      #   submit_for_review: true,
      #   force: true,
      #   reject_if_possible: true,
      #   automatic_release: true,
      #   precheck_include_in_app_purchases: false,
      # )
      upload_to_testflight(
        app_identifier: appidentifier,
        distribute_external: true,
        reject_build_waiting_for_review: true,
        expire_previous_builds: false,
        groups: [
          "Release Testing"
        ],
        submit_beta_review: true,
        notify_external_testers: true,
        changelog: releasenotes
      )
    else
      upload_to_testflight(
        app_identifier: appidentifier,
        distribute_external: true,
        reject_build_waiting_for_review: true,
        expire_previous_builds: false, # Change to true, once we make App Store releases on production deployments.
        groups: [
          "External Testers"
        ],
        submit_beta_review: true,
        notify_external_testers: true,
        changelog: commit[:message]
      )
    end
  end
end
